# Generated by Django 2.2.17 on 2020-12-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acc_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_send', to='bank.Customer')),
                ('acc_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_recieved', to='bank.Customer')),
            ],
        ),
    ]
