# Generated by Django 2.2.17 on 2020-12-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20201210_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=4, default='2020-12-10', max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfers',
            name='total',
            field=models.DecimalField(decimal_places=4, default='NULL', max_digits=22),
            preserve_default=False,
        ),
    ]
